### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by gabrielelana** [feyeleanor/GoNotebook#2]
I really like the premises of the book and its style but... 10% completion and not content for a whole year... Please give me a light of hope 😄

**Comment by feyeleanor** [comment]
Yes and no (she says 3 years 3 months later). The past four years have been a frustrating experience as just prior to the COVID-19 pandemic I cofounded a startup which has been the main focus of my efforts ever since.

That startup is currently looking like it's going to finally crash this summer, which isn't the idea outcome :/

There will definitely be more content for A Go Developer's Notebook as I have more than enough lurking from various talks I've given in recent years to easily double the current volume. And that's before even delving deeper into the topics I've already covered. Quite what that looks like I can't say just now because I don't have the time or energy to devote.

However I was serious when I said in the introduction that this is the only book I ever intend to write on Go - and quite possibly the only technical book. Whilst I'm alive there will be content begging to be added, and when I'm no longer alive the book will be finished. Well, unless I leave notes that suffer the Tolkien's Silmarillion treatment...
